package com.entity;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_id
     *
     * @mbggenerated
     */
    private int orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.seckill_id
     *
     * @mbggenerated
     */
    private int seckillId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.user_phone
     *
     * @mbggenerated
     */
    private Long userPhone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_id
     *
     * @return the value of t_order.order_id
     *
     * @mbggenerated
     */
    public int getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_id
     *
     * @param orderId the value for t_order.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.seckill_id
     *
     * @return the value of t_order.seckill_id
     *
     * @mbggenerated
     */
    public int getSeckillId() {
        return seckillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.seckill_id
     *
     * @param seckillId the value for t_order.seckill_id
     *
     * @mbggenerated
     */
    public void setSeckillId(int seckillId) {
        this.seckillId = seckillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.user_phone
     *
     * @return the value of t_order.user_phone
     *
     * @mbggenerated
     */
    public Long getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.user_phone
     *
     * @param userPhone the value for t_order.user_phone
     *
     * @mbggenerated
     */
    public void setUserPhone(Long userPhone) {
        this.userPhone = userPhone;
    }
}